[print_schema]
file = "src/schema/primary.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]

[print_schema.discuz]
schema = "discuz"
file = "src/schema/discuz.rs"
filter = { except_tables = ["^common_member_profile$"] }
